---
functional:
- Регистрация на сайте
- Авторизация с помощью Github
- Авторизация с помощью Discord
- Создание игры с ботом
- Создание игры с другим пользователем
- Создание турнира
- Доступ к игре по ссылке
- Изменение языка программирования во время игры
- Выбор уровня сложности в игре
- Выбор языка в игре (русский, английский)
- Слежение за игрой других пользователей
- Общение в чате для зарегистрированных пользователей
- Запись завершенной игры
- Получение очков по итогам игры для составления рейтинга за неделю, месяц и все время
- Запуск игры без регистрации и авторизации на сайте
- Становление премиум-подписчиком
- Просмотр своего рейтинга и рейтинга других пользователей за неделю, месяц и все время
- Вход в свой профиль
- Редактирование своего профиля
- Подсказка и сообщение об ошибке при вводе некорректных данных в форму регистрации
- Подробная информация о пользователе при клике на его профиль

non-functional:
- Сайт должен быть удобен в использовании и оптимизирован для быстрой работы.
- Сайт должен обеспечивать безопасность данных пользователей.
- Сайт должен быть удобен для использования на мобильных устройствах.
- Сайт должен быть протестирован на совместимость с последними версиями браузеров.
- Сайт должен быть способен обработать большое количество трафика (например, 1000 одновременных пользователей).
- Сайт должен отображать количество активных пользователей в режиме реального времени

implicit:
- Пользователь должен иметь возможность зарегистрироваться на сайте, указав свой номер телефона.
- Авторизованные пользователи должны иметь доступ к разделу обучения использованию      сервиса.
- Сайт должен быть доступен на двух языках: русском и английском.
- Пользователи должны иметь возможность добавлять друзей на сайте.
- Каждый пользователь должен иметь возможность указать информацию о себе в профиле.
- В профиле также должна быть возможность загрузить свою аватарку.
- При регистрации нового пользователя система должна отправить ему код подтверждения на указанный им электронный адрес, чтобы обеспечить безопасность аккаунта.
