---
functional:
  - Сайт должен быть разработан с учетом удобства использования.
  - Сайт должен быть удобным на мобильном устройстве.
  - Сайт должен быть способен обрабатывать большое количество трафика (например, 1000 одновременных пользователей).
non-functional:
  - Сайт должен быть оптимизирован для скорости работы.
  - Сайт должен быть безопасным и защищать данные пользователя.
  - Сайт должен быть протестирован на совместимость с последними версиями браузеров.
implicit:
  - Сайт должен быть на разных языках а не только на англиском.
  - У сайта должен быть интуитивно понятный для новичков интерфейс.
